name: yfl
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - annotated-types=0.7.0
  - appnope=0.1.4
  - asttokens=2.4.1
  - attrs=23.2.0
  - beautifulsoup4=4.12.3
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.7.4
  - cachetools=5.3.3
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - cryptography=42.0.8
  - debugpy=1.8.2
  - decorator=5.1.1
  - docstring_parser=0.16
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - frozenlist=1.4.1
  - geos=3.12.2
  - google-ai-generativelanguage=0.6.6
  - google-api-core=2.19.1
  - google-api-core-grpc=2.19.1
  - google-api-python-client=2.136.0
  - google-auth=2.31.0
  - google-auth-httplib2=0.2.0
  - google-cloud-aiplatform=1.58.0
  - google-cloud-bigquery-core=3.25.0
  - google-cloud-core=2.4.1
  - google-cloud-resource-manager=1.12.4
  - google-cloud-storage=2.17.0
  - google-crc32c=1.1.2
  - google-generativeai=0.7.2
  - google-resumable-media=2.7.0
  - googleapis-common-protos=1.63.2
  - googleapis-common-protos-grpc=1.63.2
  - grpc-google-iam-v1=0.13.1
  - grpcio=1.62.2
  - grpcio-status=1.62.2
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httplib2=0.22.0
  - hyperframe=6.0.1
  - idna=3.7
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libabseil=20240116.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcxx=17.0.6
  - libedit=3.1.20191231
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgrpc=1.62.2
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - matplotlib-inline=0.1.7
  - multidict=6.0.5
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.3.1
  - outcome=1.3.0.post0
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - proto-plus=1.23.0
  - protobuf=4.25.3
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.6.0
  - pyasn1-modules=0.4.0
  - pycparser=2.22
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pygments=2.18.0
  - pyopenssl=24.0.0
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyzmq=26.0.3
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.3
  - rsa=4.9
  - selenium=4.22.0
  - selenium-manager=4.22.0
  - setuptools=70.1.1
  - shapely=2.0.4
  - six=1.16.0
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - trio=0.25.1
  - trio-websocket=0.11.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - uritemplate=4.1.1
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - websocket-client=1.8.0
  - wheel=0.43.0
  - wsproto=1.2.0
  - xz=5.2.6
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.19.2
  - zstandard=0.22.0
  - zstd=1.5.6
  - pip:
      - anyio==4.4.0
      - dataclasses-json==0.6.7
      - httpcore==1.0.5
      - httpx==0.27.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.2.7
      - langchain-community==0.2.7
      - langchain-core==0.2.13
      - langchain-text-splitters==0.2.2
      - langsmith==0.1.85
      - marshmallow==3.21.3
      - mypy-extensions==1.0.0
      - numpy==1.26.4
      - ollama==0.2.1
      - orjson==3.10.6
      - pyyaml==6.0.1
      - sqlalchemy==2.0.31
      - tenacity==8.5.0
      - typing-inspect==0.9.0
